apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: YXV0aF91c2Vy
  MYSQL_PASSWORD: YXV0aF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
type: Opaque
data:
  ConnectionStrings__AuthDatabase: U2VydmVyPWF1dGgtbXlzcWw7UG9ydD0zMzA2O0RhdGFiYXNlPWF1dGhfZGI7VXNlcj1hdXRoX3VzZXI7UGFzc3dvcmQ9YXV0aF9wYXNzd29yZDtUcmVhdFRpbnlBc0Jvb2xlYW49ZmFsc2U7
