apiVersion: v1
kind: Service
metadata:
  name: webapp-ui-svc
  namespace: as-auth
spec:
  type: NodePort
  selector:
    app: webapp-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # TODO: ajustar si el profe pide otro puerto
